INSERT INTO `FINANCIAL_CONTROL`.`USUARIO` (`ID`, `NOME`, `LOGIN`, `SENHA`) VALUES (DEFAULT, 'Adminstrador', 'admin', 'admin');

INSERT INTO `FINANCIAL_CONTROL`.`BAIRRO` (`ID`, `NOME`) VALUES (DEFAULT, 'Velha');
INSERT INTO `FINANCIAL_CONTROL`.`BAIRRO` (`ID`, `NOME`) VALUES (DEFAULT, 'Garcia');
INSERT INTO `FINANCIAL_CONTROL`.`BAIRRO` (`ID`, `NOME`) VALUES (DEFAULT, 'Passo Manso');
INSERT INTO `FINANCIAL_CONTROL`.`BAIRRO` (`ID`, `NOME`) VALUES (DEFAULT, 'Fortaleza');
INSERT INTO `FINANCIAL_CONTROL`.`BAIRRO` (`ID`, `NOME`) VALUES (DEFAULT, 'Tribess');

INSERT INTO `FINANCIAL_CONTROL`.`LOGRADOURO` (`ID`, `NOME`, `BAIRRO_ID`) VALUES (DEFAULT, 'Gustavo Budag', 1);
INSERT INTO `FINANCIAL_CONTROL`.`LOGRADOURO` (`ID`, `NOME`, `BAIRRO_ID`) VALUES (DEFAULT, 'João Pessoa', 1);
INSERT INTO `FINANCIAL_CONTROL`.`LOGRADOURO` (`ID`, `NOME`, `BAIRRO_ID`) VALUES (DEFAULT, 'Marechal Deodoro', 1);

INSERT INTO `FINANCIAL_CONTROL`.`TRIBUTO` (`ID`, `NOME`, `NOME_REDUZIDO`) VALUES (DEFAULT, 'Imposto Territorial Urbano', 'IPTU');
INSERT INTO `FINANCIAL_CONTROL`.`TRIBUTO` (`ID`, `NOME`, `NOME_REDUZIDO`) VALUES (DEFAULT, 'Imposto Predial Urbano', 'IPU');
INSERT INTO `FINANCIAL_CONTROL`.`TRIBUTO` (`ID`, `NOME`, `NOME_REDUZIDO`) VALUES (DEFAULT, 'Imposto Coleta de Lixo', 'ICL');