SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `FINANCIAL_CONTROL` DEFAULT CHARACTER SET utf8 ;
USE `FINANCIAL_CONTROL` ;

CREATE TABLE IF NOT EXISTS `FINANCIAL_CONTROL`.`USUARIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `LOGIN` VARCHAR(40) NOT NULL,
  `SENHA` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `LOGIN_UNIQUE` (`LOGIN` ASC))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `FINANCIAL_CONTROL`.`TRIBUTO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(100) NOT NULL,
  `NOME_REDUZIDO` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `FINANCIAL_CONTROL`.`CONTRIBUINTE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(60) NOT NULL,
  `DATA_NASCIMENTO` DATE NOT NULL,
  `SEXO` INT NOT NULL,
  `CPFCNPJ` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `CPFCNPJ_UNIQUE` (`CPFCNPJ` ASC))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `FINANCIAL_CONTROL`.`BAIRRO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
COMMENT = '	';

CREATE TABLE IF NOT EXISTS `FINANCIAL_CONTROL`.`LOGRADOURO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(60) NOT NULL,
  `BAIRRO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_LOGRADOURO_BAIRRO_idx` (`BAIRRO_ID` ASC),
  CONSTRAINT `fk_LOGRADOURO_BAIRRO`
    FOREIGN KEY (`BAIRRO_ID`)
    REFERENCES `FINANCIAL_CONTROL`.`BAIRRO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `FINANCIAL_CONTROL`.`IMOVEL` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NUMERO` INT NOT NULL,
  `LOGRADOURO_ID` INT NOT NULL,
  `CONTRIBUINTE_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_IMOVEL_LOGRADOURO1_idx` (`LOGRADOURO_ID` ASC),
  INDEX `fk_IMOVEL_CONTRIBUINTE1_idx` (`CONTRIBUINTE_ID` ASC),
  CONSTRAINT `fk_IMOVEL_LOGRADOURO1`
    FOREIGN KEY (`LOGRADOURO_ID`)
    REFERENCES `FINANCIAL_CONTROL`.`LOGRADOURO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_IMOVEL_CONTRIBUINTE1`
    FOREIGN KEY (`CONTRIBUINTE_ID`)
    REFERENCES `FINANCIAL_CONTROL`.`CONTRIBUINTE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `FINANCIAL_CONTROL`.`LANCAMENTO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DATA_LANCAMENTO` DATE NOT NULL,
  `DATA_VENCIMENTO` DATE NOT NULL,
  `SITUACAO` INT NOT NULL,
  `VALOR` DECIMAL(15,2) NOT NULL,
  `IMOVEL_ID` INT NOT NULL,
  `TRIBTO_ID` INT NOT NULL,
  `USUARIO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_LANCAMENTO_IMOVEL1_idx` (`IMOVEL_ID` ASC),
  INDEX `fk_LANCAMENTO_TRIBTO1_idx` (`TRIBTO_ID` ASC),
  INDEX `fk_LANCAMENTO_USUARIO1_idx` (`USUARIO_ID` ASC),
  CONSTRAINT `fk_LANCAMENTO_IMOVEL1`
    FOREIGN KEY (`IMOVEL_ID`)
    REFERENCES `FINANCIAL_CONTROL`.`IMOVEL` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LANCAMENTO_TRIBTO1`
    FOREIGN KEY (`TRIBTO_ID`)
    REFERENCES `FINANCIAL_CONTROL`.`TRIBTO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LANCAMENTO_USUARIO1`
    FOREIGN KEY (`USUARIO_ID`)
    REFERENCES `FINANCIAL_CONTROL`.`USUARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';

CREATE TABLE IF NOT EXISTS `FINANCIAL_CONTROL`.`MOVIMENTO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DATA` DATE NOT NULL,
  `TIPO` INT NOT NULL,
  `VALOR` DECIMAL(15,2) NOT NULL,
  `LANCAMENTO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `LANCAMENTO_ID`),
  INDEX `fk_MOVIMENTO_LANCAMENTO1_idx` (`LANCAMENTO_ID` ASC),
  CONSTRAINT `fk_MOVIMENTO_LANCAMENTO1`
    FOREIGN KEY (`LANCAMENTO_ID`)
    REFERENCES `FINANCIAL_CONTROL`.`LANCAMENTO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
